apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: serviceaccountimports.multicluster.admiralty.io
spec:
  group: multicluster.admiralty.io
  names:
    kind: ServiceAccountImport
    plural: serviceaccountimports
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterName:
              type: string
            name:
              type: string
            namespace:
              type: string
          required:
          - clusterName
          - namespace
          - name
          type: object
        status:
          properties:
            secrets:
              items:
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
